name: aws
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=12_linux64_openblas
  - libcblas=3.9.0=12_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libgomp=11.2.0=h1d223b6_11
  - liblapack=3.9.0=12_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.11=h36c2ea0_1013
  - ncurses=6.2=h58526e2_4
  - numpy=1.22.0=py310h454958d_0
  - openssl=3.0.0=h7f98852_2
  - pandas=1.3.5=py310hb5077e9_0
  - pip=21.3.1=pyhd8ed1ab_0
  - python=3.10.1=h543edf9_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2021.3=pyhd8ed1ab_0
  - readline=8.1=h46c0cb4_0
  - setuptools=60.5.0=py310hff52083_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h9cd32fc_0
  - tk=8.6.11=h27826a3_1
  - tzdata=2021e=he74cb21_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h36c2ea0_1013
prefix: /home/xtarm/miniconda3/envs/aws
